// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA08qVXFV2S14kgZU1x2DbiN6hkQqoYLdY',
    appId: '1:572632570710:web:d2b9621cf8f4110885d4f7',
    messagingSenderId: '572632570710',
    projectId: 'to-do-app-6c100',
    authDomain: 'to-do-app-6c100.firebaseapp.com',
    storageBucket: 'to-do-app-6c100.appspot.com',
    measurementId: 'G-XS9PES29P5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV83wchQIe7bQkDg5Acq3XFVNpsMcEDlk',
    appId: '1:572632570710:android:13a06a6c34ca3df685d4f7',
    messagingSenderId: '572632570710',
    projectId: 'to-do-app-6c100',
    storageBucket: 'to-do-app-6c100.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhmux6VfG0mTQVUUpBoYq31j4aQ5ODfk4',
    appId: '1:572632570710:ios:3d6d237826a13a7285d4f7',
    messagingSenderId: '572632570710',
    projectId: 'to-do-app-6c100',
    storageBucket: 'to-do-app-6c100.appspot.com',
    iosBundleId: 'com.example.toDoApp',
  );
}
